version: '3'

services:

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
